# Linear Algebra in Python with NumPy

This notebook is a hands-on review of basic linear algebra concepts and how to use them in Python with NumPy. All code and explanations are my own, stepwise, and educational for sharing on GitHub.

**Outline:**
1. Introduction and Imports
2. Lists vs. NumPy Arrays
3. Algebraic Operators: Arrays vs. Lists
4. Matrix Creation and Pitfalls
5. Matrix Operations: Scaling, Addition, Subtraction
6. Element-wise Multiplication
7. Matrix Transpose
8. Norms and Dot Products
9. Sums and Means by Axis
10. Centering Matrices


## 1. Introduction and Imports

NumPy is the core library for array and matrix operations in Python. Let's import it and get started!

In [1]:
import numpy as np  # The swiss knife of the data scientist.

## 2. Lists vs. NumPy Arrays

Let's see the difference between a Python list and a NumPy array.

In [2]:
alist = [1, 2, 3, 4, 5]   # Define a python list. It looks like an np array
narray = np.array([1, 2, 3, 4]) # Define a numpy array

print(alist)
print(narray)
print(type(alist))
print(type(narray))

[1, 2, 3, 4, 5]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


## 3. Algebraic Operators: Arrays vs. Lists

Let's see how addition and multiplication behave differently for NumPy arrays and Python lists.

In [3]:
print(narray + narray)  # Element-wise addition
print(alist + alist)    # List concatenation

print(narray * 3)       # Element-wise scaling
print(alist * 3)        # List repetition

[2 4 6 8]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


## 4. Matrix Creation and Pitfalls

Let's see how to create matrices (arrays of arrays) in NumPy, and what happens if the rows have different lengths.

In [4]:
npmatrix1 = np.array([narray, narray, narray]) # Matrix initialized with NumPy arrays
npmatrix2 = np.array([alist, alist, alist])    # Matrix initialized with lists
npmatrix3 = np.array([narray, [1, 1, 1, 1], narray]) # Matrix with mixed types

print(npmatrix1)
print(npmatrix2)
print(npmatrix3)

# Example of a correct matrix
okmatrix = np.array([[1, 2], [3, 4]])
print(okmatrix)
print(okmatrix * 2)

# Example of a malformed matrix
badmatrix = np.array([[1, 2], [3, 4], [5, 6, 7]])
print(badmatrix)
print(badmatrix * 2)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4]
 [1 1 1 1]
 [1 2 3 4]]
[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## 5. Matrix Operations: Scaling, Addition, Subtraction

Let's see how to scale, add, and subtract matrices in NumPy.

In [5]:
# Scale by 2 and translate 1 unit the matrix
result = okmatrix * 2 + 1
print(result)

# Add two compatible matrices
result1 = okmatrix + okmatrix
print(result1)

# Subtract two compatible matrices
result2 = okmatrix - okmatrix
print(result2)

[[3 5]
 [7 9]]
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


## 6. Element-wise Multiplication

The `*` operator on arrays/matrices means element-wise multiplication, not the dot product.

In [6]:
result = okmatrix * okmatrix # Multiply each element by itself
print(result)

[[ 1  4]
 [ 9 16]]


## 7. Matrix Transpose

The transpose operator `.T` flips a matrix over its diagonal.

In [7]:
matrix3x2 = np.array([[1, 2], [3, 4], [5, 6]]) # 3x2 matrix
print('Original matrix 3 x 2')
print(matrix3x2)
print('Transposed matrix 2 x 3')
print(matrix3x2.T)

nparray = np.array([1, 2, 3, 4]) # 1D array
print('Original array')
print(nparray)
print('Transposed array')
print(nparray.T)

nparray2d = np.array([[1, 2, 3, 4]]) # 1x4 matrix
print('Original array')
print(nparray2d)
print('Transposed array')
print(nparray2d.T)

Original matrix 3 x 2
[[1 2]
 [3 4]
 [5 6]]
Transposed matrix 2 x 3
[[1 3 5]
 [2 4 6]]
Original array
[1 2 3 4]
Transposed array
[1 2 3 4]
Original array
[[1 2 3 4]]
Transposed array
[[1]
 [2]
 [3]
 [4]]


## 8. Norms and Dot Products

Let's compute the norm of vectors and matrices, and see different ways to calculate the dot product.

In [8]:
nparray1 = np.array([1, 2, 3, 4])
norm1 = np.linalg.norm(nparray1)

nparray2 = np.array([[1, 2], [3, 4]])
norm2 = np.linalg.norm(nparray2)

print(norm1)
print(norm2)

nparray3 = np.array([[1, 1], [2, 2], [3, 3]])
normByCols = np.linalg.norm(nparray3, axis=0)
normByRows = np.linalg.norm(nparray3, axis=1)
print(normByCols)
print(normByRows)

# Dot product flavors
nparray4 = np.array([0, 1, 2, 3])
nparray5 = np.array([4, 5, 6, 7])
print(np.dot(nparray4, nparray5))
print(np.sum(nparray4 * nparray5))
print(nparray4 @ nparray5)
flavor4 = 0
for a, b in zip(nparray4, nparray5):
    flavor4 += a * b
print(flavor4)

# Dot product with lists
print(np.dot([1, 2], [3, 4]))

5.477225575051661
5.477225575051661
[3.74165739 3.74165739]
[1.41421356 2.82842712 4.24264069]
38
38
38
38
11


## 9. Sums and Means by Axis

You can sum or average by rows or columns using the `axis` parameter.

In [9]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]])
sumByCols = np.sum(nparray2, axis=0)
sumByRows = np.sum(nparray2, axis=1)
print('Sum by columns: ')
print(sumByCols)
print('Sum by rows:')
print(sumByRows)

mean = np.mean(nparray2)
meanByCols = np.mean(nparray2, axis=0)
meanByRows = np.mean(nparray2, axis=1)
print('Matrix mean: ')
print(mean)
print('Mean by columns: ')
print(meanByCols)
print('Mean by rows:')
print(meanByRows)

# Static vs dynamic mean
mean1 = np.mean(nparray2)
mean2 = nparray2.mean()
print(mean1, ' == ', mean2)

Sum by columns: 
[ 6 -6]
Sum by rows:
[0 0 0]
Matrix mean: 
0.0
Mean by columns: 
[ 2. -2.]
Mean by rows:
[0. 0. 0.]
0.0  ==  0.0


## 10. Centering Matrices

Centering a matrix means subtracting the mean of each column (or row) from the elements.

In [10]:
nparray2 = np.array([[1, 1], [2, 2], [3, 3]])
nparrayCentered = nparray2 - np.mean(nparray2, axis=0)
print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered)
print('New mean by column')
print(nparrayCentered.mean(axis=0))

# Centering by rows (transpose, center, transpose back)
nparray2 = np.array([[1, 3], [2, 4], [3, 5]])
nparrayCentered = nparray2.T - np.mean(nparray2, axis=1)
nparrayCentered = nparrayCentered.T
print('Original matrix')
print(nparray2)
print('Centered by rows matrix')
print(nparrayCentered)
print('New mean by rows')
print(nparrayCentered.mean(axis=1))

Original matrix
[[1 1]
 [2 2]
 [3 3]]
Centered by columns matrix
[[-1. -1.]
 [ 0.  0.]
 [ 1.  1.]]
New mean by column
[0. 0.]
Original matrix
[[1 3]
 [2 4]
 [3 5]]
Centered by rows matrix
[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]
New mean by rows
[0. 0. 0.]
